<footer class="container-fluid bg-light p-3 position-sticky bottom-0 w-100">
    <div class="row align-items-center">
        <div class="col-md-4 text-center">
            <h5>Seguinos en redes</h5>
            <ul class="d-flex list-unstyled justify-content-center">
                <li class="mx-2">
                    <a href="https://www.facebook.com/">Facebook</a>
                </li>
                <li class="mx-2">
                    <a href="https://www.instagram.com/">Instagram</a>
                </li>
            </ul>
            <h5>Escribinos tus dudas</h5>
            <ul class="d-flex list-unstyled justify-content-center">
                <li class="mx-2">
                    <a href="https://web.whatsapp.com/">Whatsapp</a>
                </li>
            </ul>
        </div>

        <div class="col-md-4 text-center">
            <p class="mb-0">Viajes Lupa &copy; - Año 2024 -</p>
        </div>

        <div class="col-md-4 text-center">
            <h5>Dónde encontrarnos</h5>
            <p>Oficina Central</p>
            <p>Av. Corrientes 1234, CABA, Argentina</p>
            <a href="https://www.google.com/maps/place/Av.+Corrientes+1234,+C1043AAZ+Cdad.+Aut%C3%B3noma+de+Buenos+Aires/@-34.6040196,-58.3867115,17z/data=!3m1!4b1!4m6!3m5!1s0x95bccac59a5bd441:0x1408e2f06974627!8m2!3d-34.604024!4d-58.3841366!16s%2Fg%2F11c143tf76?hl=es&entry=ttu&g_ep=EgoyMDI0MTAxNi4wIKXMDSoASAFQAw%3D%3D" target="_blank">Ver en Google Maps</a>
        </div>
    </div>
</footer>

</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
