<!DOCTYPE html>
<html lang="en">
<head>
<base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>VIAJES LUPA</title>
</head>
<body>
    
</body>
</html>

<header class="container-fluid p-0">

    <nav class="navbar navbar-expand-lg navbar-light d-flex bg-light mb-4">

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav col-md-12 p-0">
                <div class="row col-md-8 justify-content-start p-0 ml-3">
                    <li class="nav-item">
                        <a href="list" class="nav-link h1" style="font-size: 2rem;">VIAJES LUPA</a> 
                    </li>
                </div>

                <div class="row col-md-4 justify-content-end p-0">
                    <li class="nav-item">
                        <a class="nav-link mr-2" id="btn-menu-login" href='ingresar'>Ingresar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="btn-menu-register" href='logout'>desloguearse</a>
                    </li>
                </div>
            </ul>
        </div>

    </nav>
</header>
